server:
  port: 8080
  address: 0.0.0.0 # 新增配置，监听服务器所有网卡
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/poker_game?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "040929"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Coze 智能体配置
coze:
  bot-id: 7648188401422106670
  api-token: pat_nuYvuEoi90crZ5LJayaB7JidstzBDJ8eaZ9VnRxwTbBByCMlFji5UVYY8SKIAtCt

# 日志
logging:
  level:
    com.poker: debug
